config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'

  HomeController.action_methods.each do |action|
    get "/#{action}", to: "home##{action}", as: "#{action}_page"
  end

  get 'user/imported_files', to: 'user#imported_files'
  get 'import', to: 'uploader#import'
  post 'import', to: 'uploader#upload'
  get 'user/contacts', to: 'user#contacts'
  get 'imported_files/:id/failed_registers',
      to: 'import_file#failed_registers', as: 'failed_registers'
end

app/views/partials/_footer.html.erb
<!-- Footer-->
<footer class="bg-light py-5">
    <div class="container px-4 px-lg-5"><div class="small text-center text-muted">Copyright &copy; 2021 - Company Name</div></div>
</footer>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
    <div class="container px-4 px-lg-5">
        <%= link_to "Contact Uploader Web App", root_path, class: "navbar-brand" %>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ms-auto my-2 my-lg-0">
              <% if user_signed_in? %>
                <li class="nav-item"><%= link_to "Upload Contact", import_path, class: "nav-link" %></li>
                <li class="nav-item"><%= link_to "Uploaded Files", user_imported_files_path, class: "nav-link" %></li>
                <li class="nav-item"><%= link_to "Contact List", user_contacts_path, class: "nav-link" %></li>
                <li class="nav-item"><%= link_to "Update my account", edit_user_registration_path, class: "nav-link" %></li>
                <li class="nav-item"><%= link_to 'Log Out', destroy_user_session_path, class: "nav-link", method: :delete %></li>
              <% else %>
                <li class="nav-item">
                  <%= link_to 'Sign In', new_user_session_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link" %>
                </li>
              <% end %>
            </ul>
        </div>
    </div>
</nav>