config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'

  HomeController.action_methods.each do |action|
    get "/#{action}", to: "home##{action}", as: "#{action}_page"
  end

  get 'user/imported_files', to: 'user#imported_files'
  get 'import', to: 'uploader#import'
  post 'import', to: 'uploader#upload'
  get 'user/contacts', to: 'user#contacts'
  get 'imported_files/:id/failed_registers',
      to: 'import_file#failed_registers', as: 'failed_registers'
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:,
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable
  has_many :import_files
  has_many :contacts
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def imported_files
    @imported_files = current_user.import_files.
                        paginate(page: params[:page], per_page: 10).
                        order('created_at DESC')
  end

  def contacts
    @contacts = current_user.contacts.
                  paginate(page: params[:page], per_page: 10).
                  order('name ASC')
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/contacts.html.erb
<br> <br>
<br> <br>


<h1>Contacts List</h1>

<div class="flickr_pagination">
  <%= will_paginate @contacts, :container => false %>
</div>
<% if @contacts.empty? %>
  <div><p>No Contacts</p></div>
<% else %>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Birthdate</th>
        <th>Phone</th>
        <th>Address</th>
        <th>Credit Card</th>
        <th>Franchise</th>
        <th>Email</th>
      </tr>
    </thead>
    <tbody>
      <% @contacts.each do |contact| %>
        <tr>
          <td><%= contact.name %></td>
          <td><%= contact.birthdate.to_date.strftime("%Y %B %d") %></td>
          <td><%= contact.phone %></td>
          <td><%= contact.address %></td>
          <td><%= contact.credit_card %></td>
          <td><%= contact.franchise %></td>
          <td><%= contact.email %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<div class="flickr_pagination mb-4">
  <%= will_paginate @contacts, :container => false %>
</div>

app/views/user/imported_files.html.erb
<br> <br>
<br> <br>

<h1>Uploaded file list</h1>

<div class="flickr_pagination">
  <%= will_paginate @imported_files, :container => false %>
</div>
<% if @imported_files.empty? %>
  <div><p>No uploaded files</p></div>
<% else %>
  <table>
    <thead>
      <tr>
        <th>Filename</th>
        <th>File created at</th>
        <th>Status</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @imported_files.each do |import| %>
        <tr>
          <td><%= import.file.filename.to_s %></td>
          <td><%= import.created_at %></td>
          <td><%= import.status %></td>
          <% if import.failed_registers.empty? %>
            <td>No errors</td>
          <% else %>
            <td><%= link_to 'Failed registers', failed_registers_path(import) %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<div class="flickr_pagination mb-4">
  <%= will_paginate @imported_files, :container => false %>
</div>